// <auto-generated />
namespace StaffManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FillTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FillTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202001291945585_FillTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
